### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by arkadyb** [sixt/gomodproxy#7]
Hi,

Solution seem to have mem leaks. Running "go mod tidy" against project makes gomodproxy to allocate more than 700mb of RAM and it never deallocates. Have you seen any issues around memory consumption? 
Command used: "gomodproxy -addr :32123 -git=github.com/[private-org-name]:Users/[username]/.ssh/id_rsa"

**Comment by arkadyb** [comment]
Majority of mem seem to be hold in git client routines:
`----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                      7542064.66kB 94.57% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).resolveObject (inline)
                                       433187.75kB  5.43% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).indexObjects (inline)
7975252.40kB 31.17% 31.17% 7975252.40kB 31.17%                | github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing.(*MemoryObject).Write
----------------------------------------------------------+-------------
                                      7916693.09kB   100% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).resolveDeltas
7866331.07kB 30.75% 61.92% 7916693.09kB 30.94%                | github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).get
----------------------------------------------------------+-------------
                                      7541567.54kB   100% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.applyPatchBase
7541567.54kB 29.48% 91.40% 7541567.54kB 29.48%                | github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.PatchDelta
----------------------------------------------------------+-------------
                                      1540267.07kB   100% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).Parse
789539.37kB  3.09% 94.49% 1540269.61kB  6.02%                | github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).indexObjects
                                       433187.75kB 28.12% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing.(*MemoryObject).Write (inline)
                                       151355.98kB  9.83% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Scanner).NextObject
                                        76484.28kB  4.97% |   github.com/[company-name]/gomodproxy/vendor/gopkg.in/src-d/go-git.v4/storage/memory.(*ObjectStorage).SetEncodedObject`

**Comment by zserge** [comment]
@arkadyb You are completely right about the origins of memory usage, but I still think it's not a memory leak.

`gomodproxy` uses go-git client to fetch Git repos, which in its turn stores git references and objects in memory, thus consuming a significant amount of RAM. This is expected and is arguably avoidable when dealing with large repositories. Once the repository is processed and a snapshot is prepared - the memory can be cleaned up.

Then, Go garbage collector uses GOGC environment variable to decide when it should trigger the collection. Default value is 100, which means the GC is triggered when memory consumption grows twice comparing the last GC cycle. I.e. if you have 100MB allocated - next GC will happen when you allocated at least 200MB.

In `gomodproxy` all operations are handled in parallel, so multiple Git repositories are processed at once, and that allocated memory is still in use for some time because fetching a snapshot of a certain revision from a repo might be a time consuming operation. This means that you may have hundreds of megabytes allocated and still in use for some time. When GC happens at this point - it notices that memory usage is still hundreds of MB, and will wait until it grows x2 before it gets triggered again. This will probably never happen and if you have enough RAM - it will remain occupied by the gomodroxy process.

You may try tweaking GOGC value to something smaller and see how your memory usage changes. I tried running `GOGC=1 gcvis gomodproxy ....` to see a visualization of memory consumption. I see big spikes of memory usage that last for a few seconds and then get cleaned up. I assume you should see something similar.

So we have two potential issues here:

1) GC is not triggered to clean up large chunks of memory that were consumed by go-git because of a high GOGC threshold.
2) gomodproxy consumes too much memory at once because of the distributed nature of its operation. Perhaps we should add a way to restrict a number of "workers" that handle the repositories to avoid dramatic growth of memory usage at the very beginning.
